### PR TITLE
feat(VirtualServer): Add cross-region cloning to pvc-clone.sh

### PR DESCRIPTION
**Pull request by ChandonPierre**
This PR adds the ability to clone a PVC between regions to `pvc-clone.sh`

### CODE REVIEW

**Comment by ChandonPierre** [comment]
Yes, it is quite slow. The recommendation is still one base disk created per region, this just adds another option.

**Comment by salanki** [comment]
Let's discuss how to improve this.

**Comment by salanki** [comment]
I'm reopening because it would be great if we could solve this in a way that people can just clone via a DataVolume.

**Comment by salanki** [comment]
Kyverno could possibly help us out here by adding an annotation on the copy-pod created by the CDI to run in the source region.

**Comment by salanki** [comment]
@ChandonPierre: You just built this for linux, can we commit it to docs?

**Pull request closed without merging**
